-- Phase 22.3a — video_ideas table.
--
-- One row per (influencer, batch_date, rank). The nightly
-- video_ideas_loop (services/video_ideas.py, 22.3b) writes ~5 ideas
-- per active bot per day; the creator-facing endpoint
-- GET /api/v1/influencers/{id}/video-ideas returns the latest batch.
--
-- The UNIQUE (influencer_id, batch_date, rank) constraint serves two
-- purposes: deduplicates the nightly loop (it can be re-run safely
-- without producing duplicates), and pins the per-bot batch shape
-- to "exactly N ranks per day" — rank 1..N maps to the chips mobile
-- renders.
--
-- status starts at 'fresh'; mobile flips to 'used' via
-- POST /video-ideas/{idea_id}/used when the creator taps Create.
-- used_at records when. These two columns are the Create-tap metric
-- gating future expansion to user-profile ideas.
--
-- idx_video_ideas_influencer_recent is the hot index for the
-- creator-facing GET (latest batch for one bot). The UNIQUE
-- constraint already implies an index suitable for the dedup probe.
--
-- Apply manually after pg_dump per Rule 9.

CREATE TABLE IF NOT EXISTS video_ideas (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    influencer_id TEXT NOT NULL REFERENCES ai_influencers(id) ON DELETE CASCADE,
    batch_date    DATE NOT NULL,
    rank          SMALLINT NOT NULL,
    hook          TEXT NOT NULL,
    idea_text     TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'fresh',
    used_at       TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT now(),
    UNIQUE (influencer_id, batch_date, rank)
);

CREATE INDEX IF NOT EXISTS idx_video_ideas_influencer_recent
    ON video_ideas (influencer_id, created_at DESC);

COMMENT ON TABLE video_ideas IS
    'Phase 22.3 — nightly-generated video idea chips per AI influencer.
     Generated by services/video_ideas.py, surfaced via
     GET /api/v1/influencers/{id}/video-ideas (owner-only).';

COMMENT ON COLUMN video_ideas.status IS
    '''fresh'' (default) | ''used'' (creator tapped Create). Drives
     the Create-tap metric that gates v1.1 user-profile ideas.';
